# Generated by Django 5.2.17 on 2026-08-26 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('tier', models.CharField(choices=[('TIER_1', 'Bangalore Flagship / High Footfall'), ('TIER_2_3', 'Tier-2/3 Regional (Mysore, Hubli, etc.)')], max_length=10)),
                ('monthly_budget_weight', models.FloatField(default=1.0)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('BUDGET', 'Budget Phone (₹6k - ₹15k)'), ('MID', 'Mid-Range (₹15k - ₹40k)'), ('FLAGSHIP', 'Flagship (₹40k - ₹1.5L)')], max_length=10)),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('launch_week', models.IntegerField(default=1)),
                ('is_eol', models.BooleanField(default=False)),
                ('successor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.phonemodel')),
            ],
        ),
        migrations.CreateModel(
            name='SalesRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField()),
                ('units_sold', models.IntegerField(default=0)),
                ('stock_available', models.IntegerField(default=0)),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.phonemodel')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.store')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField()),
                ('allocated_units', models.IntegerField()),
                ('capital_allocated', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reasoning_rupees', models.TextField()),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.phonemodel')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.store')),
            ],
        ),
    ]
